### ISSUE TITLE
Fairy Tale Busters

### ISSUE THREAD

**Issue by trevor2024** [malortie/SourceModPatcher#9]
Hi, please add support for Fairy Tale Busters.
https://archive.org/details/merubasu-setup

**Comment by malortie** [comment]
Unfortunately, I won't be able to add it.

1. This is a standalone Source engine game and not a mod. The scope of SourceModPatcher is currently limited to mods. See [here](https://github.com/malortie/SourceModPatcher/discussions/2).

2. The gameinfo.txt contains `InstancePath` which according to [VDC](https://developer.valvesoftware.com/wiki/Gameinfo.txt) is only available as of Source 2013 (2013 engine branch), making it Steampipe. SourceModPatcher's scope is limited to Pre-Steampipe engine branches (Source 2006/2007). See [here](https://github.com/malortie/SourceModPatcher/discussions/2).

3. Even if standalone Source games (including Source 2013+) were in the project's scope, the game is unplayable. The page you linked has the following link:

   https://web.archive.org/web/20170725134121/http://merubasu.playgra.com/top/index

   which leads to another page on which it's written (translated using AI):

   > Regarding "Meruhen Busters," which has been provided since February 14, 2017, we will be terminating the service on July 18, 2017. We sincerely thank you for your support thus far. In conjunction with the service termination, all game data for "Meruhen Busters" will be deleted.

   See also here: https://vghe.net/fairy-tale-busters.html

   It's possible the game relies on master servers. Since they're down, the game can't connect, making it impossible to play. The archive doesn't seem to include any tools or programs to run dedicated servers. The only available programs appear to be client related: AxiomPatcher.exe, gameclient.exe, MBGameLauncher.exe.

   To make it work minimal, a decicated server tool would need to be available and the client code would have to be changed to allow server browsing like in regular Source games. The game's source code doesn't appear to be available, which means the only way is by recreating it through reverse-engineering, or patching the DLL. In both ways, it's a lot of work and outside the scope of SourceModPatcher.

Feel free to submit other Source mods (not standalone games) you wish to see added.

Thanks.
